### ISSUE TITLE
SaveEditor.exe wont launch

### ISSUE THREAD

**Issue by bWildcard** [PixelRick/CyberpunkSaveEditor#23]
I am unable to launch this program.  Please help.

I have installed https://aka.ms/vs/16/release/vc_redist.x64.exe
I have tried running in compatibility mode and running as admin

Running win10 with all latest drivers

Windows 10 Home
Version    20H2
Installed on    ‎9/‎10/‎2020
OS build    19042.867
Experience    Windows Feature Experience Pack 120.2212.551.0

**Comment by PixelRick** [comment]
Maybe you have an antivirus that is too careful with raw executables (not signed, no icon, etc..) ?
It could also be about the directory it is in, check that the path doesn't contain weird characters (russian, spanish, korean directory name) since it could be a problem when opening the db/config files (I haven't double checked this part of the code).
Also, have you tried older versions and the pre-release ? In v0.4.6-alpha.3 you'll find a *_Debug.exe version that should pop an error window.

As an advice, don't run things as admin when they do not work. It is unsafe and usually never solves such problem.

**Comment by bWildcard** [comment]
I have No AV installed.

The path is
C:\Users\PC\Desktop\CP2077 SE\SaveEditor.exe
tried changing to CP77 root DIR

Tried 4.6 alpha3 and the latest neither work. Literally nothing happens.

**Comment by PixelRick** [comment]
Here is a debug version which should popup a message box "startup":
https://github.com/PixelRick/CyberpunkSaveEditor/releases/tag/win10-issue-test
If this box appears then the problem is with the windowing/rendering, otherwise it would be a mystery for me.
Do you have d3d11.dll and D3DCOMPILER_47.dll in your system32 ?

**Comment by PixelRick** [comment]
Timeout !
