### ISSUE TITLE
Is there a way to reset attribute points ?

### ISSUE THREAD

**Issue by LikeVII** [PixelRick/CyberpunkSaveEditor#38]
It's my first time using this mod and i was wondering if there was a way to reset attribute points by using this mod ?
Thanks for your hard work and good luck in the future !

**Comment by PixelRick** [comment]
In "Scriptable Systems/PlayerDevelopmentSystem/playerData".
This will show you an array of shared PlayerDevelopmentData.
Each has the fields: owner, ownerID, ..., proficiencies and attributes. The last two are what you are looking for.
BUT, you have to find the correct index in the array first, because it can be for other characters.
Yours is the one with ownerID equal to 1 (it is supposed to be at index 0, the first one, but better check).

btw: field 'owner' value display is big and empty for no real reason, i'll fix that.

**Comment by PixelRick** [comment]
If CyberCAT doesn't get updated in March, I'll try to make my editor more user friendly.

**Comment by LikeVII** [comment]
Thanks for your help ! i'll try to make it work, and again good luck in the future and thank you !
